### ISSUE TITLE
Add Docker image as a deployment target

### ISSUE THREAD

**Issue by rrotter** [projecthydra-labs/ansible-sufia7-playbook#23]
Docker image should be a deployment target option

**Comment by grosscol** [comment]
Build a docker image that has the entire stack + application?  The alternative is two docker images.  One for the restful services (solr, fedora, resque/jobque) and the other for the application + command line stuff (puma, sufia, ffmpeg, fits.sh, libreoffice, ect...)

Relevant ansible module: http://docs.ansible.com/ansible/docker_image_module.html
